[package]
name = "fig"
version = "0.3.0"
authors = ["Stephen Cirner <scirner@figure.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
ctrlc = "3.1"
dirs = "3.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
walkdir = "2.3"
quick-error = "2.0"
